"""empty message

Revision ID: 8d8de8c2cf47
Revises: 
Create Date: 2020-07-30 15:52:34.910065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8de8c2cf47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'gender',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.alter_column('player', 'position',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'position',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.alter_column('player', 'gender',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    # ### end Alembic commands ###
